# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 20
  tensorboard_logdir: tensorboard

checkpoint:
  keep_last_epochs: 3
  best_checkpoint_metric: wer

task:
  _name: scribblelens
  data: /pio/scratch/2/jch/wav2vec/data/scribblelens
  vocab_path: '${env:PWD}/fairseq/data/handwriting/tasman.alphabet.plus.space.mode5.json'
  enable_padding: True
  pad_to_multiples_of: 4
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false
  labels: True

dataset:
  num_workers: 0
  max_tokens: 10000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 10000
  validate_interval: 1000
  valid_subset: test

distributed_training:
  distributed_world_size: 1
  ddp_backend: no_c10d

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 13000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0

